version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  commands:
    # FIXME: dependencies should not be explicitly listed here!
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv venv
    - uv pip install .[docs]
    - rm -rf docs/source/api
    - .venv/bin/python -m sphinx.ext.apidoc
      --private
      --module-first
      --force
      --output-dir docs/source/api
      workflow/src
      workflow/rules
    - .venv/bin/python -m sphinx -T -b html -d docs/_build/doctrees -D
      language=en docs/source $READTHEDOCS_OUTPUT/html
